### ISSUE TITLE
[Bug]: FD signed a policy in the past and destination not Bangkok

### ISSUE THREAD

**Issue by PakPeter** [etherisc/flightdelay-ui#116]
### What happened?

I just signed a protection for yesterday (see the date and time in the right corner). The final destination is not Bangkok.
![01_Bug](https://github.com/user-attachments/assets/c71f7e27-20a8-461f-b057-1d839af080e1)

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by PakPeter** [comment]
Air Asia flight FD 397 is the flight I will be taking from Bali to Bangkok.

**Comment by PakPeter** [comment]
Yesterday's date was the default value. The earliest date a policy can be concluded should be entered here.

**Comment by doerfli** [comment]
assuming you used https://flightdelay.integration.etherisc.com thats on purpose as we allow to purachase flights in the past for testing purposes.
