### ISSUE TITLE
[Bug]:  FD says no matching flight, google search shows available flight

### ISSUE THREAD

**Issue by PakPeter** [etherisc/flightdelay-ui#117]
### What happened?

![02_Bug](https://github.com/user-attachments/assets/b77fed29-18af-44b9-9c00-081e1b206659)
![03_Bug](https://github.com/user-attachments/assets/a7c45f3e-6c01-4476-8ac3-f8c9f36d6c9c)
FD reports no matching flight, but a Google search shows an available flight. VietJet is VJ901 according to Google, but VJC901 according to FD.

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by matthiaszimmermann** [comment]
another one: CX885 on 2024-10-22 is available but not available on 2024-10-23 (shown as available via www.skyscanner.ch)

**Comment by doerfli** [comment]
flightstats does not provide enough data for this flight ti protect it. will change the error message accordingly. fix with #108.
