### ISSUE TITLE
Deactivate purchase button if purchase isn't possible

### ISSUE THREAD

**Issue by christoph2806** [etherisc/flightdelay-ui#140]
The "Purchase Protection" button should be disabled when one of the following conditions is true:
* while no flight is selected
* if the USDC balance isn't sufficient
* if capacity isn't sufficient
* if cluster risk prohibits protection
A self explaining message should be displayed in any of these cases.

(Implementation only if it can be done efficiently)

**Comment by doerfli** [comment]
disabling action buttons is a ux anti-pattern that should be avoided. we show an error that should help the user continue once clicked. 

https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/

**Comment by christoph2806** [comment]
Ok but clicking a non-working button and THEN see the error message which could have been shown before, is no less frustrating ...
The author in the article above suggests some alternatives. 
e.g this one: 

![image](https://github.com/user-attachments/assets/4d2ea298-9ccf-44d1-ab36-e55488cbdccd)
So include the error message near to the button.
