### ISSUE TITLE
Show USDC balance in the top right corner 

### ISSUE THREAD

**Issue by christoph2806** [etherisc/flightdelay-ui#141]
The USDC balance should be show next to the Account jazzicon.

**Comment by doerfli** [comment]
current implementation is the same as uniswap uses. the balance is shown when the jazzicon is clicked. do you really want to change it? 

<img width="527" alt="Flightdelay" src="https://github.com/user-attachments/assets/6ce31343-c679-4158-93ed-f48de59fecca">

**Comment by christoph2806** [comment]
OK wasn't aware of that. We should stay with the standards.
