### ISSUE TITLE
Local arrival and departure times not written as Strings when creating new policies.

### ISSUE THREAD

**Issue by matthiaszimmermann** [etherisc/flightdelay-ui#143]
When extracting the local arrival and departure times from FlightProduct.FlightRisk it seems that these times are stored as encoded bytes (and not strings)

example for base int environment: calling function getRiskData with NFT ID: 80845304
see https://basescan.org/address/0xf7912d59Fa78BFCB8711Af6dfE36474a56a990ec#readContract

 riskId bytes8, flightData string, departureTimeLocal string, arrivalTimeLocal string, status bytes1, delayMinutes int256

[ getRiskData(uint96) method Response ]
  riskId   bytes8 :  0x0000000000000000
  flightData   string :  QR 23 DOH MAN 20241021
  departureTimeLocal   string :  0x323032342d31302d32315431343a32353a30302e30303020417369612f5161746172
  arrivalTimeLocal   string :  0x323032342d31302d32315431393a35303a30302e303030204575726f70652f4c6f6e646f6e
  status   bytes1 :  0x4c
  delayMinutes   int256 :  0

**Comment by doerfli** [comment]
fixed with #142
