### ISSUE TITLE
Provide backend API for policy NFT ID metadata

### ISSUE THREAD

**Issue by matthiaszimmermann** [etherisc/flightdelay-ui#144]
A flght delay specific NFT contract is used to to provide flight contract specific token URI values via smart contract.

for an example, see: https://basescan.org/address/0xf7912d59Fa78BFCB8711Af6dfE36474a56a990ec#readContract
for function tokenURI with NFT ID 80845304 the following string is returned:

https://flightdelay.integration.etherisc.com/api/nft/80845304

"https://flightdelay.integration.etherisc.com/api/nft/" represents the base URI that can be set by the contract owner via setBaseURI. 

the api server should return a standard NFT metadata json for the token URI address. as an initial implementation the flght delay specific NFT contract provides the view function getMetadataJson(), individual policy related data fields are provided with function getRiskData()

ideally the NFT metadata json also provides a link to a logo image. see https://docs.immutable.com/products/zkevm/contracts/erc721/#metadata

once this is available, the flightdelay ui could present NFT ID as links that link to the NFT contract

**Comment by doerfli** [comment]
which fields should be returned? all fields from `getMetadataJson` and `getRiskData`? 
Which logo should be used (etherisc?) and what fields should contains the url?  What format should the logo be? what size?

**Comment by matthiaszimmermann** [comment]
{ 
"name": "Etherisc Policy NFT - #<token ID>",
"description": "This NFT represents a flight delay protection policy\n
Origin:        Bahrein (BAH)\n
Destination:   Bangkok\n
Flight Number: GF 86\n
Departure:     ...\n
Arrival:       ...\n
⚠️ DISCLAIMER: Due diligence is imperative when assessing this NFT.",
"image": "data:image/svg+xml;base64,..."
}

**Comment by matthiaszimmermann** [comment]
1st version implemented: see [https://flightdelay.app/api/nft/74845304](https://flightdelay.app/api/nft/74845304)
